'use strict';

export const IJ = [
  {
    name: 'Mary Beth Ingram',
    // cohort: 'Juicy Functions',
    email: 'mbingramm@gmail.com',
    github: 'https://github.com/mbingram',
    linkedin: 'https://www.linkedin.com/in/mbingram',
    medium: null,
    website: 'https://www.marybethdev.com/',
  },
  {
    name: 'Danny Irwin',
    // codepen: 'https://codepen.io/Dirwin',
    // cohort: 'Team 404',
    email: 'dirwin123@gmail.com',
    github: 'https://github.com/dannyirwin',
    linkedin: 'https://www.linkedin.com/in/dannyirwin/',
    medium: null,
    website: 'https://dannyirwin.github.io/PersonalWebpage/',
  },
  {
    name: 'Zachary Jacobs',
    // cohort: 'Notorious Git',
    email: 'zprogrammer@icloud.com',
    github: 'https://github.com/zprogrammer-code',
    linkedin: 'https://www.linkedin.com/in/zachary-jacobs-10b3351b5/',
    medium: null,
    website: null,
  },
  {
    name: 'Douglas Johnson',
    // cohort: 'Die Prying',
    // blogger: 'https://blog.dougj.dev/',
    email: 'doug@dougj.dev',
    github: 'https://github.com/Douglas-J-Johnson',
    linkedin: 'https://www.linkedin.com/in/douglas-j-johnson/',
    medium: null,
    website: 'https://dougj.dev/',
  },
  {
    name: 'Kevin Johnson',
    // cohort: 'Illicit Syntax',
    email: 'Kevin.Michael805@gmail.com',
    github: 'https://github.com/Kevin805',
    linkedin: 'https://www.linkedin.com/in/kevin-johnson805/',
    medium: null,
    website: null,
  },
  {
    name: 'Lisa Jung',
    // cohort: 'Notorious Git',
    // dev: 'https://dev.to/lisahjung',
    email: 'lisahjung@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/lisahjung/',
    medium: null,
    // twitter: 'https://twitter.com/LisaHJung',
    website: null,
  },
];
