'use strict';

export const KL = [
  {
    name: 'Tiffany Kanjanabout',
    // cohort: 'Only Spans',
    email: null,
    github: 'https://github.com/tiffanynk',
    linkedin: 'https://www.linkedin.com/in/tiffany-kanjanabout/',
    medium: 'https://tiffany-nit-k.medium.com/',
    website: null,
  },
  {
    name: 'Haley Kelling',
    // cohort: 'Empryers',
    email: 'haley@kellings.com',
    github: 'https://github.com/haleykelling',
    linkedin: 'https://www.linkedin.com/in/haley-kelling/',
    medium: null,
    website: null,
  },
  {
    name: 'Paige Kelly',
    // cohort: 'Hackstreet {Boiz}',
    email: 'paigekellydev@gmail.com',
    github: 'https://github.com/paigekellydev',
    linkedin: 'https://www.linkedin.com/in/paige-kelly-denver/',
    // linkedin: 'https://www.linkedin.com/in/paigekellydev/',
    medium: null,
    website: null,
  },
  {
    name: 'Bryce Kennedy',
    // cohort: 'Empryers',
    email: 'bryce@brycekennedy.net',
    github: 'https://github.com/btken88',
    linkedin: 'https://www.linkedin.com/in/bryce-kennedy/',
    medium: null,
    website: 'https://brycekennedy.net/',
  },
  {
    name: 'Shelley (Brook) Kershaw',
    // cohort: 'Git Forked',
    email: 'sbrook13@gmail.com',
    github: 'https://github.com/sbrook13',
    linkedin: 'https://www.linkedin.com/in/sbrook13/',
    medium: null,
    website: null,
  },
  {
    name: 'Tony Kim',
    // cohort: 'Run Time Terrors',
    email: 'hjkmines@gmail.com',
    github: 'https://github.com/hjkmines',
    linkedin: 'https://www.linkedin.com/in/hyung-kim/',
    medium: 'https://medium.com/@hjkmines',
    website: 'https://hjkmines.github.io/my-portfolio-website/',
  },
  {
    name: 'Austin Kohler',
    // cohort: 'Notorious Git',
    // dev: 'https://dev.to/austinckohler',
    email: 'austinckohler@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/austin-kohler/',
    medium: null,
    website: 'https://austinckohler.github.io/unit_9/',
  },
  {
    name: 'Allen Lea',
    // cohort: 'Illicit Syntax',
    email: 'allenlea2007@gmail.com',
    github: 'https://github.com/Allen70',
    linkedin: 'https://www.linkedin.com/in/allen-r-lea/',
    medium: null,
    website: null,
  },
  {
    name: 'Eric Lee',
    // cohort: 'Hackstreet {Boiz}',
    email: 'e.lee.at@gmail.com',
    github: 'https://github.com/Kwayzaar',
    linkedin: 'https://www.linkedin.com/in/ericmlee05/',
    medium: null,
    website: null,
  },
  {
    name: 'Louis Leffler',
    email: 'louisleffler@gmail.com',
    github: 'https://github.com/1ouis1effler',
    linkedin: 'https://www.linkedin.com/in/louisleffler/',
    medium: null,
    website: null,
  },
  {
    name: 'Kat Leight',
    // cohort: 'Hip Hip Arrays',
    email: 'leightkt@gmail.com',
    github: 'https://github.com/leightkt',
    linkedin: 'https://www.linkedin.com/in/kat-leight/',
    medium: 'https://kat-leight.medium.com/',
    website: null,
  },
  {
    name: 'Marcos Lipic',
    // cohort: 'Only Spans',
    email: 'mjlipic.37@gmail.com',
    github: 'https://github.com/Marcoslipic',
    linkedin: 'https://www.linkedin.com/in/marcos-lipic/',
    medium: 'https://marcos-lipic.medium.com/',
    website: null,
  },
  {
    name: 'Phong Lo',
    // cohort: 'Juicy Functions',
    email: 'phonglo724@gmail.com',
    github: 'https://github.com/phonglo724',
    linkedin: 'https://www.linkedin.com/in/phong-lo',
    medium: null,
    website: null,
  },
  {
    name: 'Matt Long',
    // cohort: 'Run Time Terrors',
    email: 'mdlong34@gmail.com',
    github: 'https://github.com/MattLong34',
    linkedin: 'https://www.linkedin.com/in/mattlong34/',
    medium: 'https://mattlong34.medium.com/',
    website: 'https://matt-long.dev/',
  },
  {
    name: 'JT Lu',
    // cohort: 'Notorious Git',
    email: 'alohajt94@gmail.com',
    github: 'https://github.com/alohajt',
    linkedin: 'https://www.linkedin.com/in/jt-lu-68917394/',
    medium: 'https://medium.com/@alohajt94',
    website: 'https://jtlu.dev/',
  },
  {
    name: 'Steven Ly',
    // cohort: 'Hackstreet {Boiz}',
    email: 'steven.ly0392@gmail.com',
    github: 'https://github.com/stevenly03',
    linkedin: 'https://www.linkedin.com/in/stevenly03/',
    medium: null,
    website: null,
  },
];
