'use strict';

export const OP = [
  {
    name: "Colton O'Connor",
    // cohort: 'Hip Hip Arrays',
    email: 'colton.shawn.oconnor@gmail.com',
    github: 'https://github.com/bigdumbbaby',
    linkedin: 'https://www.linkedin.com/in/colton-o-connor/',
    medium: 'https://colton-shawn-oconnor.medium.com/',
    website: 'https://coltonoconnor.com/',
  },
  {
    name: 'Jay Oliver',
    // cohort: 'Git Forked',
    email: 'jaykamas@gmail.com',
    github: 'https://github.com/Qwerter49',
    linkedin: 'https://www.linkedin.com/in/jay-oliver-29678b1b4/',
    medium: null,
    website: null,
  },
  {
    name: 'Kelsey Oshiro',
    // cohort: 'Only Spans',
    email: 'kelsocode@gmail.com',
    github: 'https://github.com/kelseymosh',
    linkedin: 'https://www.linkedin.com/in/kelseyoshiro/',
    medium: 'https://kelseymosh.medium.com/',
    website: 'https://kelseyoshiro.com/',
  },
  {
    name: 'Bryan Oyloe',
    // cohort: 'Git Forked',
    email: 'boyloe@gmail.com',
    github: 'https://github.com/boyloe',
    linkedin: 'https://www.linkedin.com/in/bryan-oyloe/',
    medium: 'https://medium.com/@bryanoyloe',
    website: 'https://bryanoyloe.com/',
  },
  {
    name: 'Jordan Panasewicz',
    // cohort: 'Illicit Syntax',
    email: 'jbpanasewicz@gmail.com',
    github: 'https://github.com/JorPan',
    linkedin: 'https://www.linkedin.com/in/jordan-panasewicz',
    medium: 'https://jorpantech.medium.com/',
    website: null,
  },
  {
    name: 'Mandy Parson',
    // cohort: 'Team 404',
    email: 'mandykparson@gmail.com',
    github: 'https://github.com/mandykparson',
    linkedin: 'https://www.linkedin.com/in/mandy-parson/',
    medium: 'https://mandykparson.medium.com/',
    website: 'https://mandy-parson-portfolio.herokuapp.com/',
  },
  {
    name: 'Jack Perry',
    // cohort:'JSON Derulo',
    email: 'jack.e.perry@outlook.com',
    github: 'https://github.com/japerry911',
    linkedin: 'https://www.linkedin.com/in/jack-e-perry/',
    medium: 'https://jack72828383883.medium.com/',
    website: 'http://www.thejackperry.com/',
  },
  {
    name: 'Kyle Peterson',
    // cohort: 'Empryers',
    email: 'kpete2017@gmail.com',
    github: 'https://github.com/kpete2017',
    linkedin: 'https://www.linkedin.com/in/kyle-petersen-27259b18b/',
    medium: null,
    website: 'https://kylepetersen.dev/',
  },
  {
    name: 'Jessica Pope',
    // cohort: null,
    email: 'jessica.pope.co@gmail.com',
    github: 'https://github.com/JdPope',
    linkedin: 'https://www.linkedin.com/in/jessica-pope-77903033/',
    medium: null,
    website: 'https://jessepope.dev/',
  },
];
