'use strict';

export const QR = [
  {
    name: 'Alison Quaglia',
    // codepen: 'https://codepen.io/hylobates-lar',
    // cohort: null,
    email: null,
    github: 'https://github.com/hylobates-lar',
    linkedin: 'https://www.linkedin.com/in/alison-quaglia/',
    medium: 'https://medium.com/@alison.quaglia',
    website: null,
  },
  {
    name: 'Michael Ramirez',
    // cohort: 'Team 404,
    email: 'stevemr77@gmail.com',
    github: 'https://github.com/stevemr77',
    linkedin: 'https://www.linkedin.com/in/stevemr77/',
    medium: null,
    website: 'https://stevemr77.github.io/my_first_website/',
  },
  {
    name: 'Will Reeves',
    // cohort: 'Empryers',
    email: 'stevemr77@gmail.com',
    github: 'https://github.com/stevemr77',
    linkedin: 'https://www.linkedin.com/in/stevemr77/',
    medium: null,
    website: 'https://stevemr77.github.io/my_first_website/',
  },
  {
    name: 'Alice Richardson',
    // cohort:'JSON Derulo',
    email: 'Paradafaii28@gmail.com',
    github: 'https://github.com/Alicerichardson28',
    linkedin: 'https://www.linkedin.com/in/alice-richardson-dev/',
    medium: 'https://alicerichardson28.medium.com/',
    website: 'https://alice-portfolio.web.app/',
  },
  {
    name: 'Hailey Ringier',
    // cohort: 'Run Time Terrors',
    email: 'haileyringier@outlook.com',
    github: 'https://github.com/haileyringier',
    linkedin: 'https://www.linkedin.com/in/hailey-ringier/',
    medium: 'https://medium.com/@haileyringier',
    website: null,
    // youtube: 'https://www.youtube.com/channel/UCv8YpacxVgL9ShVduwb3Blg',
  },
  {
    name: 'Meagan Ritchie',
    // cohort: 'Hackstreet {Boiz}',
    email: 'meaganritchie@gmail.com',
    github: 'https://github.com/MeaganRitchie',
    linkedin: 'https://www.linkedin.com/in/meagan-ritchie-tech/',
    medium: null,
    website: null,
  },
  // {
  //   name: 'Summer Rizzo',
  //   cohort: null,
  //   dev: 'https://dev.to/rizz0s',
  //   email: null,
  //   github: null,
  //   linkedin: null,
  //   medium: null,
  //   website: null,
  // },
  {
    name: 'Marnie Robinson',
    // cohort: 'Juicy Functions',
    email: 'marnielane@gmail.com',
    github: 'https://github.com/Marnielane',
    linkedin: 'https://www.linkedin.com/in/marnie-robinson/',
    medium: null,
    website: null,
  },
  {
    name: 'Reed Roffis',
    // cohort: 'Juicy Functions',
    email: 'reedroffis18@gmail.com',
    github: 'https://github.com/reedroffis',
    linkedin: 'https://www.linkedin.com/in/reed-roffis-3a9261110/',
    medium: null,
    website: null,
  },
  {
    name: 'Tony Roscioli',
    // cohort: 'Team 404',
    email: 'adrprogramming@gmail.com',
    github: 'https://github.com/TonyRosh',
    linkedin: 'https://www.linkedin.com/in/tony-rosciol-dev/',
    medium: null,
    website: null,
  },
  {
    name: 'Arielle Ross',
    // cohort: 'Hip Hip Arrays',
    email: 'arielle@arielleross.com',
    github: 'https://github.com/rel-ross',
    linkedin: 'https://www.linkedin.com/in/arielleross/',
    medium: 'https://arielle-10415.medium.com/',
    website: 'https://arielleross.com/',
  },
  {
    name: 'Benjamin Rowe',
    // cohort: 'Git Forked',
    email: 'browe495@gmail.com',
    github: 'https://github.com/benjamin787/',
    linkedin: 'https://www.linkedin.com/in/ben-rowe-tech/',
    medium: null,
    website: null,
  },
  {
    name: 'Blake Runyon',
    // cohort: 'Juicy Functions',
    email: 'blakerunyon09@gmail.com',
    github: 'https://github.com/blakerunyon09',
    linkedin: 'https://www.linkedin.com/in/blakerunyon/',
    medium: null,
    website: 'https://kaylinanorton.com/',
  },
  {
    name: 'Diana Rybikov',
    // cohort: 'Juicy Functions',
    email: 'diana.ryb214@gmail.com',
    github: 'https://github.com/dianarybikov',
    linkedin: 'https://www.linkedin.com/in/diana-rybikov-465018202/',
    medium: null,
    website: null,
  },
];
