'use strict';

export const ST = [
  {
    name: 'Justin Sabath',
    // cohort: 'Empryers',
    email: 'justin.sabath.dev@gmail.com',
    github: 'https://github.com/jsabath',
    linkedin: 'https://www.linkedin.com/in/justinsabath/',
    medium: null,
    website: 'https://jsabath.github.io/',
  },
  {
    name: 'Jack Sanders',
    // cohort: 'Only Spans',
    email: 'jack.sanders.xyz@gmail.com',
    github: 'https://github.com/jacksanders-xyz',
    linkedin: 'https://www.linkedin.com/in/jack-sanders-xyz/',
    medium: 'https://jack-sanders-xyz.medium.com/',
    website: 'https://jacksanders.xyz/',
    // youtube: 'https://www.youtube.com/channel/UCHN-T5MPbfVViZW3QAb8_Cw',
  },
  {
    name: 'Jorge Santos',
    // cohort: 'Die Prying',
    email: 'Jlsantos280@gmail.com',
    github: 'https://github.com/Jsantos107',
    linkedin: 'https://www.linkedin.com/in/santos-jorge/',
    medium: 'https://medium.com/@JorgeSantos7',
    website: 'https://jorgesantos-38e0a.firebaseapp.com/',
  },
  {
    name: 'Iuliia Saprykina',
    // cohort: 'Notorious Git',
    email: 'iuliia.proskurnina@gmail.com',
    github: 'https://github.com/IuliiaSaprykina',
    linkedin: 'https://www.linkedin.com/in/iuliia-saprykina-ab3351100/',
    medium: 'https://iuliia-proskurnina.medium.com/',
    website: 'https://portfolio-saprykina.firebaseapp.com/',
  },
  {
    name: 'Adam Shappy',
    // cohort: 'Die Prying',
    email: 'ajs11300@gmail.com',
    github: 'https://github.com/mrshappy0',
    linkedin: 'https://www.linkedin.com/in/adam-shappy/',
    medium: 'https://medium.com/@adam_shappy',
    website: 'https://adam-shappy.com/',
  },
  {
    name: 'JoAnn Siciliano',
    // cohort: 'Hackstreet {Boiz}',
    email: 'joannsiciliano.dev@gmail.com',
    github: 'https://github.com/joannsiciliano/',
    linkedin: 'https://www.linkedin.com/in/joannsiciliano/',
    medium: null,
    website: null,
  },
  {
    name: 'Scott Singer',
    // cohort: 'Empryers',
    email: 'ssinger303@gmail.com',
    github: 'https://github.com/Sc0tticus',
    linkedin: 'https://www.linkedin.com/in/scottlsinger/',
    medium: 'https://medium.com/@ssinger303',
    website: null,
  },
  {
    name: 'Alexander Sherwin',
    // cohort: 'Juicy Functions',
    email: 'alx.sherwin@gmail.com',
    github: 'https://github.com/MomentaiBro',
    linkedin: 'https://www.linkedin.com/in/alexander-sherwin/',
    medium: null,
    website: null,
  },
  {
    name: 'Rodney Smith',
    // cohort: 'Only Spans',
    email: 'r_smith3@hotmail.com',
    github: 'https://github.com/rsmithII',
    linkedin: 'https://www.linkedin.com/in/rod-smithii/',
    medium: null,
    website: null,
  },
  {
    name: 'Daniel Steed',
    // cohort: 'Notorious Git',
    email: 'dsteed112@gmail.com',
    github: 'https://github.com/dsteed112',
    linkedin: 'https://www.linkedin.com/in/daniel-steed/',
    medium: 'https://medium.com/@dsteed112',
    website: 'https://danielsteed.com/',
  },
  {
    name: 'Elliott Stein',
    // cohort: 'Git Forked',
    email: 'estein1988@gmail.com',
    github: 'https://github.com/estein1988',
    linkedin: 'https://www.linkedin.com/in/steinelliott/',
    medium: null,
    website: null,
  },
  {
    name: 'Jared Stromberg',
    // cohort: null,
    email: null,
    github: 'https://github.com/jstrombe19',
    linkedin: 'https://www.linkedin.com/in/jared-s-122690143/',
    medium: 'https://medium.com/@jaredstromberg',
    website: null,
  },
  {
    name: 'Lucas Thinnes',
    // cohort: 'Hip Hip Arrays',
    email: 'lukethinnes@protonmail.com',
    github: 'https://github.com/lukethinnes',
    linkedin: 'https://www.linkedin.com/in/lucas-thinnes/',
    medium: 'https://lucasthinnes.medium.com/',
    website: 'https://lucasthinnes.com/',
  },
  {
    name: 'Kyle Trahan',
    // cohort: 'Git Forked',
    email: 'ktrahan2@gmail.com',
    github: 'https://github.com/ktrahan2',
    linkedin: 'https://www.linkedin.com/in/kyletrahan/',
    medium: null,
    website: 'https://dev.to/ktrahan2',
  },
];
