'use strict';

export const WX = [
  {
    name: 'Harley Warson',
    // cohort: 'Hackstreet {Boiz}',
    email: 'haleywarson@gmail.com',
    github: 'https://github.com/haleywarson',
    linkedin: 'https://www.linkedin.com/in/haleywarson/',
    medium: null,
    website: null,
  },
  {
    name: 'Benton Westergaard',
    // cohort: 'Juicy Functions',
    email: 'benton.westergaard@gmail.com',
    github: 'https://github.com/bwesterg',
    linkedin: 'https://www.linkedin.com/in/benton-westergaard/',
    medium: null,
    website: null,
  },
  {
    name: 'Bob Whitmer',
    // cohort: 'Empryers',
    email: 'rjwhitmercc@gmail.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/rjwhitmer/',
    medium: null,
    website: null,
  },
  {
    name: 'Cassandra Whitty',
    // cohort: null,
    email: 'cassandraallexwhitty@gmail.com',
    github: 'https://github.com/cassandrawhitty',
    linkedin: 'https://www.linkedin.com/in/cassandra-whitty-0a184a1a4/',
    medium: null,
    website: 'https://cassandrawhitty.com/',
  },
  {
    name: 'Amber Williams',
    // cohort: null,
    email: 'awilliams1234@live.com',
    github: null,
    linkedin: 'https://www.linkedin.com/in/amber-williams-38151716b/',
    medium: null,
    website: null,
  },
  {
    name: 'Ashley Winters',
    // cohort: 'Notorious Git',
    email: 'ashbwinters@gmail.com',
    github: 'https://github.com/ashbwinters',
    linkedin: 'https://www.linkedin.com/in/ashley-winters/',
    medium: null,
    website: null,
  },
  {
    name: 'Blake Woodruff',
    // cohort: 'Notorious Git',
    email: 'blakewoodruff4@gmail.com',
    github: 'https://github.com/Bwoodruff4',
    linkedin: 'https://www.linkedin.com/in/blakewoodruffengineer/',
    medium: null,
    website: null,
  },
  {
    name: 'Angelo Xenakis',
    // cohort: null,
    // dribble: 'https://dribbble.com/AngeloTheThird',
    email: 'evangelosalexander@gmail.com',
    github: 'https://github.com/angeloxenakis/',
    linkedin: 'https://www.linkedin.com/in/angeloxenakis/',
    medium: 'https://medium.com/@angeloxenakis',
    website: 'http://www.angeloxenakis.com/',
  },
];
